set(BUILD_LVGL_FROM_NECTO "TRUE" CACHE STRING "" FORCE)
set(CMAKE_ADDR2LINE "C:/Users/klasn/AppData/Local/MIKROE/NECTOStudio7/packages/compilers/gcc/arm/gcc-arm-none-eabi/bin/arm-none-eabi-addr2line.exe" CACHE STRING "" FORCE)
set(CMAKE_AR "C:/Users/klasn/AppData/Local/MIKROE/NECTOStudio7/packages/compilers/gcc/arm/gcc-arm-none-eabi/bin/arm-none-eabi-ar.exe" CACHE STRING "" FORCE)
set(CMAKE_ASM_COMPILER "C:/Users/klasn/AppData/Local/MIKROE/NECTOStudio7/packages/compilers/gcc/arm/gcc-arm-none-eabi/bin/arm-none-eabi-gcc.exe" CACHE STRING "" FORCE)
set(CMAKE_ASM_COMPILER_AR "C:/Users/klasn/AppData/Local/MIKROE/NECTOStudio7/packages/compilers/gcc/arm/gcc-arm-none-eabi/bin/arm-none-eabi-gcc-ar.exe" CACHE STRING "" FORCE)
set(CMAKE_ASM_COMPILER_RANLIB "C:/Users/klasn/AppData/Local/MIKROE/NECTOStudio7/packages/compilers/gcc/arm/gcc-arm-none-eabi/bin/arm-none-eabi-gcc-ranlib.exe" CACHE STRING "" FORCE)
set(CMAKE_ASM_COMPILER_WORKS "1" CACHE STRING "" FORCE)
set(CMAKE_ASM_FLAGS_DEBUG "-g" CACHE STRING "" FORCE)
set(CMAKE_ASM_FLAGS_MINSIZEREL "-Os -DNDEBUG" CACHE STRING "" FORCE)
set(CMAKE_ASM_FLAGS_RELEASE "-O3 -DNDEBUG" CACHE STRING "" FORCE)
set(CMAKE_ASM_FLAGS_RELWITHDEBINFO "-O2 -g -DNDEBUG" CACHE STRING "" FORCE)
set(CMAKE_BUILD_TYPE "Debug" CACHE STRING "" FORCE)
set(CMAKE_CACHEFILE_DIR "c:/Users/klasn/FT800_Demo/build-UNI DS v8" CACHE STRING "" FORCE)
set(CMAKE_CACHE_MAJOR_VERSION "3" CACHE STRING "" FORCE)
set(CMAKE_CACHE_MINOR_VERSION "30" CACHE STRING "" FORCE)
set(CMAKE_CACHE_PATCH_VERSION "5" CACHE STRING "" FORCE)
set(CMAKE_COMMAND "C:/Users/klasn/AppData/Local/MIKROE/NECTOStudio7/packages/CMake/bin/cmake.exe" CACHE STRING "" FORCE)
set(CMAKE_CPACK_COMMAND "C:/Users/klasn/AppData/Local/MIKROE/NECTOStudio7/packages/CMake/bin/cpack.exe" CACHE STRING "" FORCE)
set(CMAKE_CTEST_COMMAND "C:/Users/klasn/AppData/Local/MIKROE/NECTOStudio7/packages/CMake/bin/ctest.exe" CACHE STRING "" FORCE)
set(CMAKE_CXX_COMPILER "C:/Users/klasn/AppData/Local/MIKROE/NECTOStudio7/packages/compilers/gcc/arm/gcc-arm-none-eabi/bin/arm-none-eabi-g++.exe" CACHE STRING "" FORCE)
set(CMAKE_C_COMPILER "C:/Users/klasn/AppData/Local/MIKROE/NECTOStudio7/packages/compilers/gcc/arm/gcc-arm-none-eabi/bin/arm-none-eabi-gcc.exe" CACHE STRING "" FORCE)
set(CMAKE_C_COMPILER_AR "C:/Users/klasn/AppData/Local/MIKROE/NECTOStudio7/packages/compilers/gcc/arm/gcc-arm-none-eabi/bin/arm-none-eabi-gcc-ar.exe" CACHE STRING "" FORCE)
set(CMAKE_C_COMPILER_RANLIB "C:/Users/klasn/AppData/Local/MIKROE/NECTOStudio7/packages/compilers/gcc/arm/gcc-arm-none-eabi/bin/arm-none-eabi-gcc-ranlib.exe" CACHE STRING "" FORCE)
set(CMAKE_C_FLAGS_DEBUG "-g" CACHE STRING "" FORCE)
set(CMAKE_C_FLAGS_MINSIZEREL "-Os -DNDEBUG" CACHE STRING "" FORCE)
set(CMAKE_C_FLAGS_RELEASE "-O3 -DNDEBUG" CACHE STRING "" FORCE)
set(CMAKE_C_FLAGS_RELWITHDEBINFO "-O2 -g -DNDEBUG" CACHE STRING "" FORCE)
set(CMAKE_DLLTOOL "C:/msys64/ucrt64/bin/dlltool.exe" CACHE STRING "" FORCE)
set(CMAKE_EDIT_COMMAND "C:/Users/klasn/AppData/Local/MIKROE/NECTOStudio7/packages/CMake/bin/cmake-gui.exe" CACHE STRING "" FORCE)
set(CMAKE_EXECUTABLE_FORMAT "ELF" CACHE STRING "" FORCE)
set(CMAKE_EXPORT_COMPILE_COMMANDS "1" CACHE STRING "" FORCE)
set(CMAKE_FIND_PACKAGE_REDIRECTS_DIR "C:/Users/klasn/FT800_Demo/build-UNI DS v8/CMakeFiles/pkgRedirects" CACHE STRING "" FORCE)
set(CMAKE_GENERATOR "Ninja" CACHE STRING "" FORCE)
set(CMAKE_HOME_DIRECTORY "C:/Users/klasn/FT800_Demo" CACHE STRING "" FORCE)
set(CMAKE_INSTALL_BINDIR "bin" CACHE STRING "" FORCE)
set(CMAKE_INSTALL_DATAROOTDIR "share" CACHE STRING "" FORCE)
set(CMAKE_INSTALL_INCLUDEDIR "include" CACHE STRING "" FORCE)
set(CMAKE_INSTALL_LIBDIR "lib" CACHE STRING "" FORCE)
set(CMAKE_INSTALL_LIBEXECDIR "libexec" CACHE STRING "" FORCE)
set(CMAKE_INSTALL_LOCALSTATEDIR "var" CACHE STRING "" FORCE)
set(CMAKE_INSTALL_OLDINCLUDEDIR "/usr/include" CACHE STRING "" FORCE)
set(CMAKE_INSTALL_PREFIX "C:/Users/klasn/FT800_Demo/install" CACHE STRING "" FORCE)
set(CMAKE_INSTALL_SBINDIR "sbin" CACHE STRING "" FORCE)
set(CMAKE_INSTALL_SHAREDSTATEDIR "com" CACHE STRING "" FORCE)
set(CMAKE_INSTALL_SYSCONFDIR "etc" CACHE STRING "" FORCE)
set(CMAKE_LINKER "C:/Users/klasn/AppData/Local/MIKROE/NECTOStudio7/packages/compilers/gcc/arm/gcc-arm-none-eabi/bin/arm-none-eabi-ld.exe" CACHE STRING "" FORCE)
set(CMAKE_MAKE_PROGRAM "C:/MikroElektronika/MikroElektronika/NECTOStudio/bin/ninja.exe" CACHE STRING "" FORCE)
set(CMAKE_NM "C:/Users/klasn/AppData/Local/MIKROE/NECTOStudio7/packages/compilers/gcc/arm/gcc-arm-none-eabi/bin/arm-none-eabi-nm.exe" CACHE STRING "" FORCE)
set(CMAKE_NUMBER_OF_MAKEFILES "1" CACHE STRING "" FORCE)
set(CMAKE_OBJCOPY "C:/Users/klasn/AppData/Local/MIKROE/NECTOStudio7/packages/compilers/gcc/arm/gcc-arm-none-eabi/bin/arm-none-eabi-objcopy.exe" CACHE STRING "" FORCE)
set(CMAKE_OBJDUMP "C:/Users/klasn/AppData/Local/MIKROE/NECTOStudio7/packages/compilers/gcc/arm/gcc-arm-none-eabi/bin/arm-none-eabi-objdump.exe" CACHE STRING "" FORCE)
set(CMAKE_PLATFORM_INFO_INITIALIZED "1" CACHE STRING "" FORCE)
set(CMAKE_PREFIX_PATH "C:/Users/klasn/FT800_Demo/install" CACHE STRING "" FORCE)
set(CMAKE_PROJECT_NAME "FT800_Demo" CACHE STRING "" FORCE)
set(CMAKE_RANLIB "C:/Users/klasn/AppData/Local/MIKROE/NECTOStudio7/packages/compilers/gcc/arm/gcc-arm-none-eabi/bin/arm-none-eabi-ranlib.exe" CACHE STRING "" FORCE)
set(CMAKE_READELF "C:/Users/klasn/AppData/Local/MIKROE/NECTOStudio7/packages/compilers/gcc/arm/gcc-arm-none-eabi/bin/arm-none-eabi-readelf.exe" CACHE STRING "" FORCE)
set(CMAKE_ROOT "C:/Users/klasn/AppData/Local/MIKROE/NECTOStudio7/packages/CMake/share/cmake-3.30" CACHE STRING "" FORCE)
set(CMAKE_SKIP_INSTALL_RPATH "NO" CACHE STRING "" FORCE)
set(CMAKE_SKIP_RPATH "NO" CACHE STRING "" FORCE)
set(CMAKE_STRIP "C:/Users/klasn/AppData/Local/MIKROE/NECTOStudio7/packages/compilers/gcc/arm/gcc-arm-none-eabi/bin/arm-none-eabi-strip.exe" CACHE STRING "" FORCE)
set(CMAKE_TAPI "CMAKE_TAPI-NOTFOUND" CACHE STRING "" FORCE)
set(CMAKE_TOOLCHAIN_FILE "C:/Users/klasn/FT800_Demo/build-UNI DS v8/toolchain.cmake" CACHE STRING "" FORCE)
set(CMAKE_VERBOSE_MAKEFILE "FALSE" CACHE STRING "" FORCE)
set(CORE_NAME "M7" CACHE STRING "" FORCE)
set(FLATTEN_ME "TRUE" CACHE STRING "" FORCE)
set(FLATTEN_ME_LEVEL "FLATTEN_ME_LEVEL_HIGH" CACHE STRING "" FORCE)
set(FT800_Demo_BINARY_DIR "C:/Users/klasn/FT800_Demo/build-UNI DS v8" CACHE STRING "" FORCE)
set(FT800_Demo_IS_TOP_LEVEL "ON" CACHE STRING "" FORCE)
set(FT800_Demo_SOURCE_DIR "C:/Users/klasn/FT800_Demo" CACHE STRING "" FORCE)
set(HAS_MIKROBUS "true" CACHE STRING "" FORCE)
set(IS_PD_SETUP "FALSE" CACHE STRING "" FORCE)
set(LOG_INTERFACE "LOG_INTERFACE_STDOUT" CACHE STRING "" FORCE)
set(MCU_FLASH "1048576" CACHE STRING "" FORCE)
set(MCU_IS_DUALCORE "0" CACHE STRING "" FORCE)
set(MCU_NAME "STM32F745VG" CACHE STRING "" FORCE)
set(MCU_RAM "327680" CACHE STRING "" FORCE)
set(MIKROSDK_TYPE "mikrosdk" CACHE STRING "" FORCE)
set(MSDK_BUILD_TFT_MODULES "TRUE" CACHE STRING "" FORCE)
set(MikroC.Core_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroC.Core" CACHE STRING "" FORCE)
set(MikroSDK.Board_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroSDK.Board" CACHE STRING "" FORCE)
set(MikroSDK.Driver.ADC_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroSDK.Driver.ADC" CACHE STRING "" FORCE)
set(MikroSDK.Driver.CAN_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroSDK.Driver.CAN" CACHE STRING "" FORCE)
set(MikroSDK.Driver.DMA_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroSDK.Driver.DMA" CACHE STRING "" FORCE)
set(MikroSDK.Driver.GPIO.In_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroSDK.Driver.GPIO.In" CACHE STRING "" FORCE)
set(MikroSDK.Driver.GPIO.Out_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroSDK.Driver.GPIO.Out" CACHE STRING "" FORCE)
set(MikroSDK.Driver.GPIO.Port_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroSDK.Driver.GPIO.Port" CACHE STRING "" FORCE)
set(MikroSDK.Driver.I2C.Master_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroSDK.Driver.I2C.Master" CACHE STRING "" FORCE)
set(MikroSDK.Driver.OneWire_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroSDK.Driver.OneWire" CACHE STRING "" FORCE)
set(MikroSDK.Driver.PWM_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroSDK.Driver.PWM" CACHE STRING "" FORCE)
set(MikroSDK.Driver.RTC_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroSDK.Driver.RTC" CACHE STRING "" FORCE)
set(MikroSDK.Driver.SPI.Master_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroSDK.Driver.SPI.Master" CACHE STRING "" FORCE)
set(MikroSDK.Driver.UART_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroSDK.Driver.UART" CACHE STRING "" FORCE)
set(MikroSDK.Driver_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroSDK.Driver" CACHE STRING "" FORCE)
set(MikroSDK.Ft800_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroSDK.Ft800" CACHE STRING "" FORCE)
set(MikroSDK.GenericPointer_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroSDK.GenericPointer" CACHE STRING "" FORCE)
set(MikroSDK.GraphicLibrary_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroSDK.GraphicLibrary" CACHE STRING "" FORCE)
set(MikroSDK.Hal.ADC_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroSDK.Hal.ADC" CACHE STRING "" FORCE)
set(MikroSDK.Hal.CAN_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroSDK.Hal.CAN" CACHE STRING "" FORCE)
set(MikroSDK.Hal.DMA_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroSDK.Hal.DMA" CACHE STRING "" FORCE)
set(MikroSDK.Hal.GPIO_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroSDK.Hal.GPIO" CACHE STRING "" FORCE)
set(MikroSDK.Hal.I2C.Master_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroSDK.Hal.I2C.Master" CACHE STRING "" FORCE)
set(MikroSDK.Hal.OneWire_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroSDK.Hal.OneWire" CACHE STRING "" FORCE)
set(MikroSDK.Hal.PWM_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroSDK.Hal.PWM" CACHE STRING "" FORCE)
set(MikroSDK.Hal.RTC_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroSDK.Hal.RTC" CACHE STRING "" FORCE)
set(MikroSDK.Hal.SPI.Master_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroSDK.Hal.SPI.Master" CACHE STRING "" FORCE)
set(MikroSDK.Hal.UART_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroSDK.Hal.UART" CACHE STRING "" FORCE)
set(MikroSDK.HalInterface_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroSDK.HalInterface" CACHE STRING "" FORCE)
set(MikroSDK.HalLowLevel.ADC_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroSDK.HalLowLevel.ADC" CACHE STRING "" FORCE)
set(MikroSDK.HalLowLevel.CAN_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroSDK.HalLowLevel.CAN" CACHE STRING "" FORCE)
set(MikroSDK.HalLowLevel.DMA_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroSDK.HalLowLevel.DMA" CACHE STRING "" FORCE)
set(MikroSDK.HalLowLevel.GPIO_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroSDK.HalLowLevel.GPIO" CACHE STRING "" FORCE)
set(MikroSDK.HalLowLevel.I2C.Master_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroSDK.HalLowLevel.I2C.Master" CACHE STRING "" FORCE)
set(MikroSDK.HalLowLevel.OneWire_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroSDK.HalLowLevel.OneWire" CACHE STRING "" FORCE)
set(MikroSDK.HalLowLevel.RTC_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroSDK.HalLowLevel.RTC" CACHE STRING "" FORCE)
set(MikroSDK.HalLowLevel.SPI.Master_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroSDK.HalLowLevel.SPI.Master" CACHE STRING "" FORCE)
set(MikroSDK.HalLowLevel.TIM_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroSDK.HalLowLevel.TIM" CACHE STRING "" FORCE)
set(MikroSDK.HalLowLevel.UART_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroSDK.HalLowLevel.UART" CACHE STRING "" FORCE)
set(MikroSDK.HalLowLevelCommon_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroSDK.HalLowLevelCommon" CACHE STRING "" FORCE)
set(MikroSDK.HalLowLevelCore_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroSDK.HalLowLevelCore" CACHE STRING "" FORCE)
set(MikroSDK.MikroBus_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroSDK.MikroBus" CACHE STRING "" FORCE)
set(MikroSDK.RingBuffer_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroSDK.RingBuffer" CACHE STRING "" FORCE)
set(MikroSDK.TouchPanel_DIR "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake/MikroSDK.TouchPanel" CACHE STRING "" FORCE)
set(NECTO_APPLICATION_DIR "C:/MikroElektronika/MikroElektronika/NECTOStudio/bin" CACHE STRING "" FORCE)
set(NECTO_DESIGNER_GENERATOR_PATH "C:/MikroElektronika/MikroElektronika/NECTOStudio/bin/vtft_generator.exe" CACHE STRING "" FORCE)
set(NECTO_LVGL_VERSION "9.4.0" CACHE STRING "" FORCE)
set(OSC "216" CACHE STRING "" FORCE)
set(PREINIT_ROUTINE_PATH "C:/Users/klasn/AppData/Local/MIKROE/NECTOStudio7/packages/preinit" CACHE STRING "" FORCE)
set(PROJECT_TYPE "standard" CACHE STRING "" FORCE)
set(TEST_LIB_PATH "C:/Users/klasn/AppData/Local/MIKROE/NECTOStudio7/packages/unit_test_lib" CACHE STRING "" FORCE)
set(TOOLCHAIN_ID "gcc_arm_none_eabi" CACHE STRING "" FORCE)
set(TOOLCHAIN_LANGUAGE "GNU" CACHE STRING "" FORCE)
set(_GNUInstallDirs_LAST_CMAKE_INSTALL_PREFIX "C:/Users/klasn/FT800_Demo/install" CACHE STRING "" FORCE)
set(_HAS_MIKROBUS_ "TRUE" CACHE STRING "" FORCE)
set(_MSDK_BOARD_NAME_ "BOARD_UNI_DS_V8" CACHE STRING "" FORCE)
set(_MSDK_ETH_PHY_CHIP_ "NULL" CACHE STRING "" FORCE)
set(_MSDK_HAL_LOW_LEVEL_TARGET_ "mikroe" CACHE STRING "" FORCE)
set(_MSDK_MCU_CARD_NAME_ "MCU_CARD_31_FOR_STM32" CACHE STRING "" FORCE)
set(_MSDK_PACKAGE_ID_ "LQFP" CACHE STRING "" FORCE)
set(_MSDK_PACKAGE_NAME_ "Tx" CACHE STRING "" FORCE)
set(_MSDK_PACKAGE_PIN_COUNT_ "100" CACHE STRING "" FORCE)
set(_MSDK_TFT_BOARD_ "TFT_BOARD_4_RESISTIVE" CACHE STRING "" FORCE)
set(_MSDK_TFT_HEIGHT_ "272" CACHE STRING "" FORCE)
set(_MSDK_TFT_TP_ "__TP_STMPE811__" CACHE STRING "" FORCE)
set(_MSDK_TFT_TP_CONTROLLER_ "_DEFAULT_" CACHE STRING "" FORCE)
set(_MSDK_TFT_TP_ROTATE_ "TP_ROTATE_180" CACHE STRING "" FORCE)
set(_MSDK_TFT_TYPE_ "__TFT_RESISTIVE__" CACHE STRING "" FORCE)
set(_MSDK_TFT_WIDTH_ "480" CACHE STRING "" FORCE)
set(flatten_level "FLATTEN_ME_LEVEL_HIGH" CACHE STRING "" FORCE)
set(standard_output "Application output" CACHE STRING "" FORCE)
set(TOOLCHAIN_ID "gcc_arm_none_eabi" CACHE STRING "" FORCE)
set(OSC "216" CACHE STRING "" FORCE)

# set CMAKE_SYSTEM_NAME to define build as CMAKE_CROSSCOMPILING
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_VERSION 1)

# specify cross compilers and tools
set(CMAKE_C_COMPILER "C:/Users/klasn/AppData/Local/MIKROE/NECTOStudio7/packages/compilers/gcc/arm/gcc-arm-none-eabi/bin/arm-none-eabi-gcc.exe" CACHE INTERNAL "")
set(CMAKE_CXX_COMPILER "C:/Users/klasn/AppData/Local/MIKROE/NECTOStudio7/packages/compilers/gcc/arm/gcc-arm-none-eabi/bin/arm-none-eabi-g++.exe" CACHE INTERNAL "")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)


set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

file(TO_CMAKE_PATH "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake" MIKROSDK_PATH)
file(TO_CMAKE_PATH "C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake" MIKROC_CORE_PATH)

set(MIKROSDK_ROOT_PATH ${MIKROSDK_PATH})
set(MIKROC_CORE_ROOT_PATH ${MIKROC_CORE_PATH})
#append to cmake_prefix_path
list(APPEND CMAKE_PREFIX_PATH ${MIKROSDK_ROOT_PATH})
list(APPEND CMAKE_PREFIX_PATH ${MIKROC_CORE_ROOT_PATH})

list(APPEND CMAKE_MODULE_PATH "C:/Users/klasn/AppData/Local/MIKROE/NECTOStudio7/cmake;C:/Users/klasn/AppData/Local/MIKROE/NECTOStudio7/packages/core/ARM/gcc_clang/arm_gcc_clang_stm32f7x/cmake;C:/Users/klasn/AppData/Local/MIKROE/NECTOStudio7/packages/mikroe_utils_common;C:/Users/klasn/FT800_Demo/.meproject/setup/Debug/lib/cmake;")

if (DEFINED CORE_NAME AND NOT "${CORE_NAME}" STREQUAL "")
    include(coreUtils)
    set_flags(FLAGS)
    message(INFO ": ${FLAGS}")

    # add compiler option flags
    add_compile_options(${FLAGS})
    # add link option flags
    add_link_options(${FLAGS})
endif()



if (SDK_SETUP_BUILD)
    add_link_options(-T "%LINKER_SCRIPT%")
endif()
